apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: NodePort
  selector:
    app: capstone-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080

